source: ./docs

title: EC4 DAQ
description: EC4 DAQ
# theme: just-the-docs
remote_theme: just-the-docs/just-the-docs

url: https://nordicec.github.io/ec4daq

aux_links:
 Nordic Electrochemistry: https://nordicec.com/software/ec4-daq/
 
plugins:
 - jekyll-remote-theme
 - jekyll-paginate
 - jekyll-sitemap


